version: '3'

services:
  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
  epictale:
    build: .
    command: dart bin/server.dart
    ports:
      - "8001:8080"
    depends_on:
      - db