version: '3'

services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
  telegram:
    build: .
    command: dart bin/server.dart
    container_name: ${CONTAINER_NAME}
    ports:
      - "${TARGET_PORT}:8080"
    environment:
      - MONGO=${MONGO}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - mongo