version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  telegram:
    build: .
    command: dart bin/server.dart
    ports:
      - "7070:8080"
    depends_on:
      - mongo