name: epictale_telegram
description: Telegram bot for https://the-tale.org
version: 1.1.1
author: David Leibovych <ariedov@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.12.0
  mongo_dart: ^0.3.3
  thetale_api: ^1.0.1

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.1
